#!/bin/sh
wallpaper="girl_bar.png"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a feh state=floating
bspc rule -a Emacs state=tiled
bspc rule -a zathura state=tiled

# Set the cool cursor
xsetroot -cursor_name left_ptr &

# Compositor
picom &

# Wallpaper
nitrogen --set-zoom-fill "/home/leo/.wallpapers/$wallpaper" &

# Launching the bar
polybar -c .config/polybar/config top &

# Layout
setxkbmap fr &

# Merging Xressources
xrdb -merge /home/leo/.Xresources &

# Shortkeys
sxhkd &
