#!/bin/bash
wallpaper="gal_in_snow.jpg"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a feh state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Discord follow=off

# Boder's colors
bspc config focused_border_color "#98b6d0"
bspc config normal_border_color "#373a43"

# Shortkeys
killall sxhkd
sxhkd &

# Set the cool cursor
xsetroot -cursor_name left_ptr &

# Compositor
killall picom
picom &

# Wallpaper
killall nitrogen
nitrogen --set-zoom-fill "$HOME/.local/share/wallpapers/$wallpaper" &

# Launching the bar
killall polybar
polybar -c .config/polybar/config top &

# Merging Xressources
xrdb -merge $HOME/.Xresources

# Unlock gpg
qarma --password | gpg --passphrase-fd 0 -d $HOME/.local/share/enc &

# Start mpd
killall mpd
mpd &

# redshift
killall redshift
redshift -P -l 47:6 &
